// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/app/AppAlert.vue')['default']
    AppCard: typeof import('./src/components/app/AppCard.vue')['default']
    AppCardBoard: typeof import('./src/components/app/AppCardBoard.vue')['default']
    AppModal: typeof import('./src/components/app/AppModal.vue')['default']
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    BoardItem: typeof import('./src/components/posts/BoardItem.vue')['default']
    PostForm: typeof import('./src/components/posts/PostForm.vue')['default']
    PostItem: typeof import('./src/components/posts/PostItem.vue')['default']
    PostModal: typeof import('./src/components/posts/PostModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
